services:
  - type: web
    name: mushroom-api
    repo: https://github.com/lemonyyye/mushroom_recognize.git
    branch: main
    rootDir: mushroom-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn mushroom_api:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon